// Add valid blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlcmN1bGVzIiwiaWQiOiI2OWRhMzQzNDdiMTVlOTFkMTRiNzkwNmEiLCJpYXQiOjE3NzU5MDk2OTN9.F8epOPM0R-zlRWK1Hsi9hDLOqsu_JX-cPkAOztdkyHM

{
  "title": "My First Blog",
  "author": "Domyyy",
  "url": "https://google.com",
  "likes": 10
}