// Valid number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mr. Wayne5",
  "number": "111-3894729"
}

###

// Invalid number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mr. Wayne56",
  "number": "111-3894729gh"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "8989-89898"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Wayne",
  "number": ""
}

###

// Add person with name that is too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "J",
  "number": "87878787"
}