POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true,
  "userId": "69d7c118b283b9b0b6c4c9ae"
}

###

// Send note that is too short
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS",
  "important": true
}